<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            // ── Kaos (category_id = 1) ─────────────────────────────────────
            [
                'name'          => 'Kaos Polos Premium Pria',
                'code_product'  => 'PRD-001',
                'description'   => 'Kaos polos berbahan cotton combed 30s, lembut di kulit dan tidak mudah kusut. Tersedia dalam berbagai pilihan warna.',
                'price'         => 120000,
                'discount'      => 10,
                'final_price'   => 108000,
                'stock'         => 150,
                'category_id'   => 1,
                'size'          => 'S,M,L,XL,XXL',
                'image'         => 'products/kaos-polos-pria.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Kaos Grafis Wanita',
                'code_product'  => 'PRD-002',
                'description'   => 'Kaos grafis wanita dengan desain unik motif batik modern, berbahan katun lembut dan breathable.',
                'price'         => 135000,
                'discount'      => 0,
                'final_price'   => 135000,
                'stock'         => 80,
                'category_id'   => 1,
                'size'          => 'S,M,L,XL',
                'image'         => 'products/kaos-grafis-wanita.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Kaos Oversize Unisex',
                'code_product'  => 'PRD-003',
                'description'   => 'Kaos oversize unisex dengan potongan longgar dan nyaman, cocok untuk tampilan streetwear kekinian.',
                'price'         => 155000,
                'discount'      => 15,
                'final_price'   => 131750,
                'stock'         => 60,
                'category_id'   => 1,
                'size'          => 'M,L,XL,XXL',
                'image'         => 'products/kaos-oversize.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ── Kemeja (category_id = 2) ───────────────────────────────────
            [
                'name'          => 'Kemeja Batik Slim Fit',
                'code_product'  => 'PRD-004',
                'description'   => 'Kemeja batik motif parang dengan potongan slim fit, cocok untuk acara formal maupun semi-formal.',
                'price'         => 280000,
                'discount'      => 20,
                'final_price'   => 224000,
                'stock'         => 45,
                'category_id'   => 2,
                'size'          => 'S,M,L,XL,XXL',
                'image'         => 'products/kemeja-batik.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Kemeja Flannel Casual',
                'code_product'  => 'PRD-005',
                'description'   => 'Kemeja flannel kotak-kotak berbahan tebal dan hangat, ideal untuk cuaca dingin maupun gaya outdoor.',
                'price'         => 210000,
                'discount'      => 0,
                'final_price'   => 210000,
                'stock'         => 70,
                'category_id'   => 2,
                'size'          => 'S,M,L,XL',
                'image'         => 'products/kemeja-flannel.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ── Celana (category_id = 3) ───────────────────────────────────
            [
                'name'          => 'Celana Chino Panjang',
                'code_product'  => 'PRD-006',
                'description'   => 'Celana chino panjang berbahan twill stretch, nyaman dipakai seharian dan mudah dipadukan dengan berbagai atasan.',
                'price'         => 250000,
                'discount'      => 10,
                'final_price'   => 225000,
                'stock'         => 90,
                'category_id'   => 3,
                'size'          => '28,30,32,34,36',
                'image'         => 'products/celana-chino.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Celana Jeans Slim Fit',
                'code_product'  => 'PRD-007',
                'description'   => 'Celana jeans slim fit dengan bahan denim berkualitas, memberikan tampilan stylish dan modern.',
                'price'         => 320000,
                'discount'      => 25,
                'final_price'   => 240000,
                'stock'         => 55,
                'category_id'   => 3,
                'size'          => '28,30,32,34,36,38',
                'image'         => 'products/celana-jeans.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ── Dress (category_id = 4) ────────────────────────────────────
            [
                'name'          => 'Midi Dress Floral',
                'code_product'  => 'PRD-008',
                'description'   => 'Midi dress dengan motif bunga cantik, berbahan rayon yang adem dan jatuh. Cocok untuk pesta maupun hangout.',
                'price'         => 350000,
                'discount'      => 0,
                'final_price'   => 350000,
                'stock'         => 40,
                'category_id'   => 4,
                'size'          => 'S,M,L,XL',
                'image'         => 'products/midi-dress-floral.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Maxi Dress Polos',
                'code_product'  => 'PRD-009',
                'description'   => 'Maxi dress polos berbahan jersey lembut dengan siluet elegan, tersedia dalam berbagai pilihan warna pastel.',
                'price'         => 295000,
                'discount'      => 10,
                'final_price'   => 265500,
                'stock'         => 35,
                'category_id'   => 4,
                'size'          => 'S,M,L',
                'image'         => 'products/maxi-dress.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ── Jaket (category_id = 5) ────────────────────────────────────
            [
                'name'          => 'Jaket Bomber Premium',
                'code_product'  => 'PRD-010',
                'description'   => 'Jaket bomber berbahan nylon premium dengan lapisan fleece di dalam, hangat dan stylish untuk berbagai kesempatan.',
                'price'         => 450000,
                'discount'      => 15,
                'final_price'   => 382500,
                'stock'         => 30,
                'category_id'   => 5,
                'size'          => 'S,M,L,XL,XXL',
                'image'         => 'products/jaket-bomber.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Hoodie Fleece Unisex',
                'code_product'  => 'PRD-011',
                'description'   => 'Hoodie fleece tebal dengan kualitas premium, sangat cocok untuk cuaca dingin atau aktivitas outdoor.',
                'price'         => 380000,
                'discount'      => 0,
                'final_price'   => 380000,
                'stock'         => 50,
                'category_id'   => 5,
                'size'          => 'S,M,L,XL,XXL',
                'image'         => 'products/hoodie-fleece.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // ── Hijab (category_id = 6) ────────────────────────────────────
            [
                'name'          => 'Hijab Segi Empat Voal',
                'code_product'  => 'PRD-012',
                'description'   => 'Hijab segi empat berbahan voal lasercut anti-slip, ringan dan tidak mudah licin. Cocok untuk pemakaian sehari-hari.',
                'price'         => 85000,
                'discount'      => 0,
                'final_price'   => 85000,
                'stock'         => 200,
                'category_id'   => 6,
                'size'          => 'All Size',
                'image'         => 'products/hijab-voal.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Hijab Pashmina Ceruti',
                'code_product'  => 'PRD-013',
                'description'   => 'Hijab pashmina berbahan ceruti premium yang lembut dan mudah dibentuk, tersedia dalam berbagai pilihan warna.',
                'price'         => 95000,
                'discount'      => 5,
                'final_price'   => 90250,
                'stock'         => 180,
                'category_id'   => 6,
                'size'          => 'All Size',
                'image'         => 'products/hijab-pashmina.jpg',
                'is_active'     => true,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Kaos Raglan Pria',
                'code_product'  => 'PRD-014',
                'description'   => 'Kaos raglan pria dengan kombinasi warna kontras yang keren, bahan cotton combed 24s yang nyaman.',
                'price'         => 140000,
                'discount'      => 0,
                'final_price'   => 140000,
                'stock'         => 0,
                'category_id'   => 1,
                'size'          => 'S,M,L,XL',
                'image'         => 'products/kaos-raglan.jpg',
                'is_active'     => false,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
        ]);
    }
}
