<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            // ── Admin ──────────────────────────────────────────────────────
            [
                'first_name'        => 'Admin',
                'last_name'         => 'Hema',
                'email'             => 'admin@hema.id',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'no_telp'           => '081200000001',
                'gender'            => 'male',
                'age'               => 30,
                'role'              => 'admin',
                'address'           => 'Jl. Sudirman No. 1, Jakarta Pusat, DKI Jakarta',
                'profile_img'       => null,
                'status'            => 'active',
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],

            // ── Customers ──────────────────────────────────────────────────
            [
                'first_name'        => 'Budi',
                'last_name'         => 'Santoso',
                'email'             => 'budi.santoso@gmail.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'no_telp'           => '081234567890',
                'gender'            => 'male',
                'age'               => 25,
                'role'              => 'customer',
                'address'           => 'Jl. Kebon Jeruk No. 12, Jakarta Barat, DKI Jakarta',
                'profile_img'       => null,
                'status'            => 'active',
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'first_name'        => 'Siti',
                'last_name'         => 'Rahayu',
                'email'             => 'siti.rahayu@gmail.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'no_telp'           => '082198765432',
                'gender'            => 'female',
                'age'               => 22,
                'role'              => 'customer',
                'address'           => 'Jl. Cempaka Putih No. 5, Jakarta Timur, DKI Jakarta',
                'profile_img'       => null,
                'status'            => 'active',
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'first_name'        => 'Andi',
                'last_name'         => 'Wijaya',
                'email'             => 'andi.wijaya@yahoo.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'no_telp'           => '085612345678',
                'gender'            => 'male',
                'age'               => 28,
                'role'              => 'customer',
                'address'           => 'Jl. Diponegoro No. 88, Bandung, Jawa Barat',
                'profile_img'       => null,
                'status'            => 'active',
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'first_name'        => 'Dewi',
                'last_name'         => 'Lestari',
                'email'             => 'dewi.lestari@gmail.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'no_telp'           => '087711223344',
                'gender'            => 'female',
                'age'               => 24,
                'role'              => 'customer',
                'address'           => 'Jl. Malioboro No. 7, Yogyakarta, DIY',
                'profile_img'       => null,
                'status'            => 'active',
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'first_name'        => 'Rizky',
                'last_name'         => 'Firmansyah',
                'email'             => 'rizky.firmansyah@gmail.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'no_telp'           => '089922334455',
                'gender'            => 'male',
                'age'               => 27,
                'role'              => 'customer',
                'address'           => 'Jl. Pemuda No. 30, Surabaya, Jawa Timur',
                'profile_img'       => null,
                'status'            => 'active',
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'first_name'        => 'Nurul',
                'last_name'         => 'Hidayah',
                'email'             => 'nurul.hidayah@gmail.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'no_telp'           => '081355667788',
                'gender'            => 'female',
                'age'               => 21,
                'role'              => 'customer',
                'address'           => 'Jl. Ahmad Yani No. 15, Makassar, Sulawesi Selatan',
                'profile_img'       => null,
                'status'            => 'active',
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'first_name'        => 'Hendra',
                'last_name'         => 'Kusuma',
                'email'             => 'hendra.kusuma@outlook.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('password'),
                'no_telp'           => '082244556677',
                'gender'            => 'male',
                'age'               => 32,
                'role'              => 'customer',
                'address'           => 'Jl. Gatot Subroto No. 45, Medan, Sumatera Utara',
                'profile_img'       => null,
                'status'            => 'inactive',
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ]);
    }
}
